tasks:
  - before: brew install hub
    init: git init && git add . && git commit -m "Inital tdt4100" && hub create && git push -u origin HEAD 
    command: cd ovinger && mvn clean -Dmaven.test.skip=true package
image:
  file: .gitpod.Dockerfile

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080

vscode:
  extensions:
    - vscjava.vscode-java-pack@0.8.1:LRImBn//d5JhH4PUEI1BaQ==
    - vscjava.vscode-java-test@0.22.1:Z4zyXcgmx4SbkaGmi700Jw==
